### PR TITLE
:sparkles: Highlight microphone icon when talking

### PR DESCRIPTION
**Pull request by AnotherFoxGuy**
This PR adds a simple highlight to the microphone icon when it receives audio
This should make it way more obvious when your microphone isn't sending any audio

### CODE REVIEW

**Comment by dooly123** [comment]
will test shortly, thanks for taking the time and effort it's appreciated!

**Comment by dooly123** [comment]
ok, it will work, I will update the code to in the update loop and skip setting it if the colour hasn't changed. let me know if you want to do that tho.

**Comment by dooly123** [comment]
would fading in and out look better aswell?

**Comment by AnotherFoxGuy** [comment]
>  skip setting it if the colour hasn't changed

I can add that 

> would fading in and out look better aswell?

I was thinking of maybe scaling it up a bit when active, but I'm not sure if that would become annoying after a while

**Comment by dooly123** [comment]
only way to know is to try!

> > skip setting it if the colour hasn't changed
> 
> I can add that
> 
> > would fading in and out look better aswell?
> 
> I was thinking of maybe scaling it up a bit when active, but I'm not sure if that would become annoying after a while

**Comment by AnotherFoxGuy** [comment]
I've added some scaling to the icon, let me know if it is too much or annoying

**Comment by dooly123** [comment]
You all good love committers merging tomorrow

**Pull request merged**
