### PR TITLE
creating my own test scene

### PR DESCRIPTION
**Pull request by Joederpz**

### CODE REVIEW

**Comment by dooly123** [comment]
joe dont make a pull request to the up stream for that :)

**Comment by Joederpz** [comment]
So sorry still figuring out how to use this repo
I forked I should be able to commit and push to my repo right? I won’t pull
requests again my bad on that. 😬

**Comment by dooly123** [comment]
i am not gonna come after ya if you make a mistake. 

forking should be all you need todo :)  (as long as your pointing your repo at the fork)

**Comment by Joederpz** [comment]
Haha, thanks much appreciated!!!

**Pull request closed without merging**
